sudo: required
language: rust
rust: stable
cache: cargo
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo test -p beancount-parser
  - cd beancount-core && cargo test --features chrono
